<?php
/**
 * Task template for separate item
 *
 * @author Magento
 */

/**
 * @var $this Mediamadefresh\Task\Block\View
 * @see Mediamadefresh\Task\Block\View
 */
?>
<?php $_taskItem = $this->getTask(); ?>
    <div class="task_item_subtitle">
        <?php echo $this->formatDate($_taskItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_taskItem->getAuthor()) ?>
    </div>

<div class="task_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_taskItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_taskItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="task_item_content"><?php echo $_taskItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>